- .travis.yml
- Makefile
- cmd/adapter/adapter.go
- cmd/adapter/app/start.go
- glide.lock
- glide.yaml
- hack/gofmt-all.sh
- pkg/client/api.go
- pkg/client/interfaces.go
- pkg/client/metrics/metrics.go
- pkg/client/types.go
- pkg/custom-provider/metric_namer.go
- pkg/custom-provider/metric_namer_test.go
- pkg/custom-provider/provider.go
- pkg/custom-provider/provider_test.go
This commit sets up Travis CI to run the unit tests.
It installs glide, initializes the vendor directory,
and then runs `make test`.
Part of #11.
> [build] set up Travis CI to run the unit tests

- README.md
- docs/format.md
- docs/walkthrough.md
This adds a walkthrough to the docs covering setting up Prometheus and
the adapter, as well as autoscaling a sample application on custom
metrics.
> [docs] Add walkthrough

- docs/walkthrough.md
This fixes a typo in the walkthrough with a missing `</details>` closing
tag, and clarifies that you'll need RBAC set up for delegation.
> [docs] Minor walkthough fixes

- cmd/adapter/app/start.go
- glide.lock
- glide.yaml
- pkg/custom-provider/metric_namer_test.go
- pkg/custom-provider/provider.go
- pkg/custom-provider/provider_test.go
This updates the dependencies to be compatible with Kubernetes 1.8,
including the new custom.metrics.k8s.io/v1beta1 API group and the
corresponding custom-metrics-apiserver changes.
> Update deps for Kubernetes 1.8

- Makefile
The directory is owned by the user running make, but some files in it are owned by root since they are created by programs running within a docker container running as root. This doesn't matter, unlinking files is a write operation on the directory that contains them. Thus write access to the root-owned files isn't required.
> Use rm -rf instead of sudo when removing the temp dir

- cmd/adapter/app/start.go
- pkg/custom-provider/metric_namer.go
- pkg/custom-provider/metric_namer_test.go
- pkg/custom-provider/provider.go
- pkg/custom-provider/provider_test.go
This allows setting a prefix on the labels used to determine which
resources a series belongs to.  The prefix may be set using the
`--label-prefix` flag.
> Allow setting a resource label prefix

- README.md
- deploy/manifests/custom-metrics-apiserver-auth-delegator-cluster-role-binding.yaml
- deploy/manifests/custom-metrics-apiserver-auth-reader-role-binding.yaml
- deploy/manifests/custom-metrics-apiserver-deployment.yaml
- deploy/manifests/custom-metrics-apiserver-resource-reader-cluster-role-binding.yaml
- deploy/manifests/custom-metrics-cluster-role.yaml
- deploy/manifests/custom-metrics-resource-reader-cluster-role.yaml
- deploy/manifests/hpa-custom-metrics-cluster-role-binding.yaml
- docs/walkthrough.md
This updates the README and walkthrough to use v1.9 API versions,
and to use Prometheus v2.
> [docs] update to v1.9 API versions

- docs/walkthrough.md
when creating the custom APIService the example was missing the `create` portion of the `kubectl` command.
> Add missing `create` on api registration

- docs/walkthrough.md
The volume was mounted at `/var/run/serving/certs` but the container was sending an arg to look at `/var/run/serving-cert` (missing the trailing `s`)
> Fix serving cert path config in deployment spec

- README.md
This documents that the relist interval must be at least the Prometheus
scrape interval, lest metrics fade in and out.
Closes #77
> [docs] Advice on relist interval

- deploy/manifests/custom-metrics-apiserver-deployment.yaml
If using an image build with `FROM scratch` (as built by the
build-local-images make target), you need to explictly mount
/tmp as an emptyDir.
Fixes #80
> Explicitly mount /tmp as an emptyDir

- deploy/manifests/custom-metrics-apiserver-deployment.yaml
The configmap is mounted under /etc/adapter/config.yaml instead of /default/adapter-config.yaml
> sets the right path for config file

- deploy/README.md
This PR uses standard `kubernetes.io/tls` secret type for the adapter TLS certificates.
Also I documented a little bit in detail how the user can get this certificates ready.
I fixed the deployment so that it works. The config file reference was wrong. `/etc/adapter/config.yaml` works for me.
> Use type kubernetes.io/tls for adapter TLS certificates

- pkg/config/loader.go
UnmarshalStrict instead of Unmarshal will cause a failure if the config a users uses does not properly unmarshal into the config struct. This is nice because it will help quickly determine if you are missing something, or have a field in the wrong place.
> use strict unmarshalling to ensure correct configuration

- pkg/custom-provider/metric_namer.go
It's fairly common to have a label pattern that matches lots of
irrelevant labels, so this makes the "error" about being unable to
normalize/resolve a label to a GVR a V(9) info log, instead of an error
log.
Closes #101
> Reduce metric namer label-GVR logspam

- deploy/manifests/custom-metrics-apiserver-deployment.yaml
There was an extraneous `/adapter` in the deployment args that was
causing people issues.  This removes it.
> Remove extraneous `/adapter` from deployment args

- cmd/adapter/adapter.go
We need to be able to use another certificate to talk to Prometheus than talking to Kubernetes.
Therefore this PR adds another HTTP client that gets a certificate loaded from a ca file.
/cc @DirectXMan12 @brancz @s-urbaniak
> Support custom ca certificate to talk to Prometheus

- pkg/resourceprovider/provider.go
Fixes #147 
Tested this on my cluster and works as expected. Technically I don't see how the node list should ever be empty, but I fixed the case anyways. Also let me know if you prefer nil or empty lists rather, I have no strong opinion on either.
@DirectXMan12 @s-urbaniak @squat @metalmatze
> Fix empty pod or node list resulting in an error

- pkg/custom-provider/metric_namer.go
- pkg/custom-provider/series_registry.go
- pkg/naming/resource_converter.go
Fix issue:[#178](https://github.com/DirectXMan12/k8s-prometheus-adapter/issues/178)
Fix namespaced bug of node resource, node resource should be a
non-namespaced resource as the resource namespace.
By doing this fix, node resouce can be accessed as expected, as the issue explains.
Closes issue:[#178](https://github.com/DirectXMan12/k8s-prometheus-adapter/issues/178)
> Fix namespaced bug of node resource for issue #178

- pkg/naming/metrics_query.go
- pkg/naming/metrics_query_test.go
According to documentation LabelValuesByName is supposed to render "|" separated values.
Currently it is returned as a slice per label name. This fixes it
Fixes #191
@paulfantom: as discussed, let's add unit tests for the external metrics rendering too.
> pkg/naming: fix LabelValuesByName rendering

- pkg/external-provider/metric_converter.go
- pkg/external-provider/provider.go
- pkg/naming/metrics_query_test.go
Currently simple external scalar values don't have a value attached:
```
{
"kind": "ExternalMetricValueList",
"apiVersion": "external.metrics.k8s.io/v1beta1",
"metadata": {
"selfLink": "/apis/external.metrics.k8s.io/v1beta1/namespaces/default/http_requests_per_second"
},
"items": [
{
"metricName": "",
..
"value": "100133m"
}
]
}
```
This fixes it:
```
{
"kind": "ExternalMetricValueList",
"apiVersion": "external.metrics.k8s.io/v1beta1",
"metadata": {
"selfLink": "/apis/external.metrics.k8s.io/v1beta1/namespaces/default/http_requests_per_second"
},
"items": [
{
"metricName": "http_requests_per_second",
...
"value": "100133m"
}
]
}
```
> pkg/external-provider: set metric name for scalar values

- pkg/naming/metrics_query.go
- pkg/naming/metrics_query_test.go
Currently, the namespace is ignored for external labels.
This fixes it.
> pkg/naming/BuildExternal: respect namespace

- Makefile
This is a follow-up to #212.
- `VENDOR_DOCKERIZED` is no longer needed
- `GOIMAGE` needs to be updated. This part is not tested in CI, so it wasn't checked in #212
- setting `GO111MODULE` in Makefile should improve developer experience.
/cc @s-urbaniak
> *: use proper golang image and always set go111module in build pipeline

- Makefile
Set the default ARCH to be the ARCH of the golang environment.
> remove hard-coded amd64 arch

- docs/config.md
Small thing, but missing `-` in order to make seriesFilters an array. Ran into issues getting the example to run until I saw this https://github.com/DirectXMan12/k8s-prometheus-adapter/blob/master/docs/sample-config.yaml#L40
Just updating to reflect that structure
> Yaml typo for seriesFilters example

- docs/config.md
This was a small gotcha for me as I was setting up my configuration.
> Small typo in config example snippet

- README.md
- deploy/manifests/custom-metrics-apiservice.yaml
- deploy/manifests/custom-metrics-cluster-role.yaml
- deploy/manifests/custom-metrics-config-map.yaml
The external metrics functionality worked great for us out of the box, but getting the configuration right took some trial and error with the limited documentation. Contributing back our working example.
> Demonstrate how to use external metrics

- pkg/custom-provider/provider.go
ref: https://github.com/DirectXMan12/k8s-prometheus-adapter/issues/280
This pull-request prevents the NaN from being cast to int64. This is because the value of histogram_quantile(), which returns a NaN when the request is 0, such as calculating a custom metric for 95%tile, will overflow and returned `-9223372036854775808m`.
> Fix NaN not to be cast to int64

- cmd/adapter/adapter.go
The`--metrics-max-age` flag has been introduced in #136 with a fixed default value of 20 minutes. 
The current default value leads to the situation that when metrics drop out of Prometheus, they are still reported in the discovery information of the Custom Metrics API (`/apis/custom.metrics.k8s.io/v1beta1`) for 20 minutes.
This can be quite confusing if you don't know about the `--metrics-max-age` flag and expect the behaviour that is described in the docs. Namely that the Prometheus Adapter discovers all metrics that have been updated since the last discovery query (defined by the relist interval), which is also the reason the relist interval must be at least as large as the Prometheus scraping interval (see #229).
By setting the default value of `--metrics-max-age` equal to the relist …
> Set --metrics-max-age default value equal to relist interval

- pkg/resourceprovider/provider.go
We're experiencing an issue where HPA won't work with pods that have init containers. The root cause seems to be that the init containers have memory metrics but no CPU metrics, and HPA refuses to take action if any containers in the pod have container metrics, but are missing either CPU or memory.
This patch makes the adapter metrics look like the metrics server endpoint.
Before:
```
items:
- apiVersion: metrics.k8s.io/v1beta1
containers:
- name: gerbil
usage:
cpu: "0"
memory: 1568Ki
- name: gerbil-init
usage:
memory: "0"
kind: PodMetrics
```
After:
```
items:
- apiVersion: metrics.k8s.io/v1beta1
containers:
- name: gerbil
usage:
cpu: "0"
memory: 1568Ki
- name: gerbil-init
usage:
cpu: "0"
memory: "0"
kind: PodMetrics
```
> Populate both CPU and Memory resource container metrics if one is specified

- go.mod
- go.sum
- vendor/modules.txt
- vendor/sigs.k8s.io/metrics-server/pkg/api/node.go
- vendor/sigs.k8s.io/metrics-server/pkg/api/pod.go
Include the following fix to the NodeMetrics and PodMetrics APIs to match k8s
conventions: https://github.com/kubernetes-sigs/metrics-server/pull/654
- NodeMetrics and PodMetrics now have labels as they can be filtered by
them
- Field selector is now applied to NodeMetrics and PodMetrics instead
of Nodes and Pods
cc @s-urbaniak
> Make NodeMetrics and PodMetrics APIs match K8s conventions

- pkg/custom-provider/provider.go
When querying custom-metrics, the metric label selectors weren't populated in the resulting values.
A query with a metricLabelSelector query parameter set to `endpoint=https` was resulting in the following MetricValueList:
```
{
"kind": "MetricValueList",
"apiVersion": "custom.metrics.k8s.io/v1beta1",
...
"items": [
{
...
"selector": null
}
...
}
```
With this change, it now appears as:
```
{
"kind": "MetricValueList",
"apiVersion": "custom.metrics.k8s.io/v1beta1",
...
"items": [
{
...
"selector": {
"matchLabels": {
"endpoint": "https"
}
}
}
...
}
```
/cc @s-urbaniak
> Populate metric selector for custom metrics

- NOTICE
According to the CNCF rules to donate a repository:
```
If (a) contributor(s) have not signed the CLA and could not be reached,
a NOTICE file should be added referencing section 7 of the CLA with a
list of the developers who could not be reached.
```
> Add NOTICE to comply with the CNCF rules

- pkg/config/config.go
I wanted to create a CRD based on prometheus-adapter configuration. Sadly `controller-gen` requires `json` schema to be used in golang types files.
PR should allow using `controller-gen` and other tools to consume existing API.
/cc @dgrisonnet @s-urbaniak
> pkg/config: allow configuration to be read from json schema

- docs/walkthrough.md
fixes #378 
This PR makes sure, the ServiceMonitor and the Service port name match each other.
> fix walkthrough example

- cmd/config-gen/utils/default.go
- deploy/manifests/custom-metrics-config-map.yaml
- docs/config.md
- docs/sample-config.yaml
- pkg/custom-provider/provider_test.go
- pkg/custom-provider/series_registry_test.go
- pkg/resourceprovider/provider_test.go
This was brought up in https://github.com/kubernetes-sigs/prometheus-adapter/issues/289. The metric labels are incorrect for Kubernetes 1.16+, because the labels were [removed](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.16.md#removed-metrics).
> Fix documented metrics labels to work for k8s 1.16+

- Makefile
Update test Makefile rule to include https://github.com/kubernetes-sigs/prometheus-adapter/blob/master/cmd/adapter/adapter_test.go
/cc @s-urbaniak
> Makefile: include tests from cmd directory

- .travis.yml
The verify job has been moved to prow, so we can remove the one from
travis.
/assign @s-urbaniak
> .travis.yml: remove verify job

- deploy/README.md
Fixing links in `deploy/README.md` to no longer be broken. See issue: https://github.com/kubernetes-sigs/prometheus-adapter/issues/349
> Updating deploy/README.md to fix links

- docs/externalmetrics.md
- docs/sample-config.yaml
- pkg/config/config.go
- pkg/naming/metric_namer.go
- pkg/naming/metrics_query.go
- pkg/naming/metrics_query_test.go
- pkg/resourceprovider/provider.go
When set to false, no namespace label will be set by the adapter based on the namespace
portion of the url in the request path.
This allows individual consumers to set namespace independent of the source kubernetes resource.
---
Example:
Given an adapter config like this:
```
externalRules:
- seriesQuery: 'nsq_topic_depth'
resources:
namespaced: false
```
An HPA could target a different namespace by setting it in the selector:
```
- type: External
external:
metric:
name: nsq_topic_depth
selector:
labelSelector:
topic: my-topic
namespace: nsq
```
This is useful for scaling on metrics from services that run in a differnt namespace than the source resource.
> Allow metrics to be defined as `namespaced: false`

- Makefile
- cmd/adapter/adapter.go
- cmd/config-gen/main.go
- cmd/config-gen/utils/default.go
- go.mod
- pkg/client/fake/client.go
- pkg/client/metrics/metrics.go
- pkg/custom-provider/provider.go
- pkg/custom-provider/provider_test.go
- pkg/custom-provider/series_registry.go
- pkg/custom-provider/series_registry_test.go
- pkg/external-provider/basic_metric_lister.go
- pkg/external-provider/external_series_registry.go
- pkg/external-provider/metric_converter.go
- pkg/external-provider/periodic_metric_lister_test.go
- pkg/external-provider/provider.go
- pkg/naming/metric_namer.go
- pkg/naming/metrics_query.go
- pkg/naming/metrics_query_test.go
- pkg/naming/regex_matcher_test.go
- pkg/naming/resource_converter.go
- pkg/resourceprovider/provider.go
- pkg/resourceprovider/provider_test.go
With the move to the kubernetes-sigs organization, we renamed the go module to `github.com/kubernetes-sigs/prometheus-adapter` instead of `sigs.k8s.io/prometheus-adapter` like most of the projects in the org.
So this PR:
- Rename the go module to sigs.k8s.io/prometheus-adapter
- Reorder imports with goimports
> Move prometheus-adapter to sigs.k8s.io golang package

- .travis.yml
- cmd/adapter/adapter.go
Pod listing was broken because the informer used for the pod list watcher wasn't started.
> Fix pod lister by running the pod informer

- .travis-deploy.sh
- Dockerfile
- Makefile
Improve and cleanup container push rules to prepare for the move to the
official gcr.k8s.io registry.
As part of the improvements, I replaced the non-cross-platform busybox
image by gcr.io/distroless/static:latest which is platform agnostic.
> Improve container push rules

- Makefile
- deploy/README.md
- deploy/manifests/custom-metrics-apiserver-deployment.yaml
- docs/walkthrough.md
Default to the official gcr registries `k8s.gcr.io/prometheus-adapter` and `gcr.io/k8s-staging-prometheus-adapter` instead of https://hub.docker.com/r/directxman12/k8s-prometheus-adapter and https://quay.io/repository/coreos/k8s-prometheus-adapter-amd64.
Ref: https://github.com/kubernetes-sigs/prometheus-adapter/issues/414
> Default images to the official k8s.gcr.io and gcr.io registries

- Makefile
The IMAGE env variable is used by prow when building images, so it was
replacing what we would have expected to be the `prometheus-adapter`
image by the container image used to build the prometheus-adapter image.
Ref to the deploy failures highlighting this issue on master: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-prometheus-adapter-push-images/1410561345820037120
> Stop populating IMAGE env variable

- Makefile
Fix error seen in [CI](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-prometheus-adapter-push-images/1412400508353646592) when creating the multi-arch image manifest.
cc @fpetkovski
> Fix push-multi-arch image deployment

- cloudbuild.yaml
As per recent [CI run](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-prometheus-adapter-push-images/1412400508353646592), the current timeout of 30 minutes might be too low since it takes ~25 minutes to build all images and push them to the gcr registry.
cc @fpetkovski
> Increase cloudbuild timeout to 1h

- pkg/resourceprovider/provider.go
- pkg/resourceprovider/provider_test.go
When serving the resource metrics API, prometheus-adapter may return
negative values for pods/nodes memory and CPU usage. This happens
because Prometheus sees counter resets which results in Prometheus
interpolating data incorrectly to avoid the counter value going down.
To prevent that, we need to add some guards in prometheus-adapter to
replace the negative value with zero whenever it detects one.
/cc @s-urbaniak @fpetkovski
> Prevent prometheus-adapter from returning negative resource metrics

- pkg/custom-provider/provider.go
- pkg/external-provider/provider.go
In custom-metrics-apiserver v1.22.0, contexts were added to the metric
providers. We can benefit from that by propagating the context given to
the provider down to the requests.
> Propagate metric providers context

- README.md
Images hosted on gcr.k8s.io aren't browsable to the users, so linking to
the website results in a 403 HTTP error which is confusing.
> README: improve gcr.k8s.io instructions

- OWNERS
- OWNERS_ALIASES
Trips up some python based tools. Could we remove this since it is not being used?
Signed-off-by: Davanum Srinivas <davanum@gmail.com>
> Drop unused alias in OWNERS_ALIASES

- cmd/adapter/adapter.go
- pkg/client/api.go
We hit the limitation of HTTP request line size of a certain managed prometheus service. To avoid the limitation, we would like to use POST method to query Prometheus servers.
Docs: https://prometheus.io/docs/prometheus/latest/querying/api/#instant-queries
> You can URL-encode these parameters directly in the request body by using the POST method and Content-Type: application/x-www-form-urlencoded header. This is useful when specifying a large query that may breach server-side URL character limits.
> Add --prometheus-verb to support POST requests to prometheus servers

- deploy/manifests/custom-metrics-apiserver-deployment.yaml
Point the images to the official prometheus-adapter image in gcr.
Fixes #527
> Fix image location in manifests

- README.md
- deploy/manifests/custom-metrics-apiserver-deployment.yaml
- docs/walkthrough.md
Use new domain for k8s image registry, as per https://groups.google.com/a/kubernetes.io/g/dev/c/DYZYNQ_A6_c/m/FpHqeVR2BAAJ
More context: https://github.com/kubernetes/kubernetes/pull/109938
> Update registry location to registry.k8s.io

- cmd/adapter/adapter.go
When `--prometheus-token-file` is used, prometheus-adapter crashes with a segmentation violation error
This is caused by `httpClient.Transport` being `nil` and being dereferenced in the `BearerAuthRoundTripper`.
Fixes #478
> Fix segfault when using --prometheus-token-file

- cmd/adapter/adapter.go
Having no explicit `MinVersion` is reported by [gosec] as G402 (CWE-295): `TLS MinVersion too low`
Using MinVersion: tls.VersionTLS12 because it's what client-go uses:
https://github.com/kubernetes/client-go/blob/1ac8d459351e21458fd1041f41e43403eadcbdba/transport/transport.go#L92
That way, the Kubernetes API client and the Prometheus client in `prometheus-adapter` use the same TLS config `MinVersion`.
[gosec]: https://github.com/securego/gosec
> Set MinVersion: tls.VersionTLS12 in prometheus client's TLSClientConfig

- cmd/adapter/adapter.go
- cmd/adapter/adapter_test.go
Instead of using `logs.AddGoFlags(local)` to add logging flags to Go `flags.FlagSet`, then adding them to `github.com/spf13/pflag.FlagSet`, we directly add them to `github.com/spf13/pflag.FlagSet`.
/kind cleanup
> Refactor adding logging flags

- .golangci.yml
- pkg/resourceprovider/provider.go
Similar to https://github.com/kubernetes-sigs/custom-metrics-apiserver/pull/128
`earliestTs` is renamed `earliestTS` to comply to [Go naming conventions](https://github.com/golang/go/wiki/CodeReviewComments#initialisms).
> golangci-lint: Add stylecheck linter

- go.mod
- go.sum
Cf. https://pkg.go.dev/vuln/GO-2022-1144
> Bump golang.org/x/net to v0.4.0 for GO-2022-1144

- test/run-e2e-tests.sh
/kind cleanup
/kind deprecation
There are still references to https://storage.googleapis.com/kubernetes-release instead of https://dl.k8s.io/
dl.k8s.io is the correct advertised download host and will eventually move to be fastly shielding a fully community-owned bucket
ref: https://github.com/kubernetes/k8s.io/issues/2396
> fix: use dl.k8s.io, not kubernetes-release bucket

- cmd/adapter/adapter.go
until the Go standard library and golang.org/x/net are fully fixed.
---
Manually tested using `curl -sI --http2 -k -w "%{http_version}\n" -o /dev/null https://localhost:6443` (after changing the base image to get `curl`). It returns `1.1` when `--disable-http2` is set.
I could add an e2e test but it'll take some time.
> Add a toggle to disable HTTP/2 on the server to mitigate CVE-2023-44487
