Makefile, deploy/Dockerfile
=> Update Makefile to release and build for multiple platforms

deploy/README.md, deploy/example-deployment.yaml
Basically setting things up so you can access it via API Aggregation in an RBAC-enabled cluster as well
@DirectXMan12 PTAL
=> Add RBAC and API Aggregation rules to example manifest

Makefile
Very small fix, just to make my scripts happy :)
=> add option to fetch vendor dockerized

README.md, cmd/adapter/app/start.go, glide.lock, glide.yaml, pkg/client/api.go, pkg/client/interfaces.go, pkg/custom-provider/metric_namer.go, pkg/custom-provider/metric_namer_test.go, pkg/custom-provider/provider.go, pkg/custom-provider/provider_test.go
This PR contains a bunch of cleanups of leftover TODOs from the initial PoC.  There's still a couple more that I'd like to clean up, and I have to do some manual end to end tests before I merge this.
=> Cleanups from initial development

.travis-deploy.sh, .travis.yml
This tags new images every commit (via Travis) as latest, and every
tag gets pushed as a separate tag as well.
Closes #38
=> [infra] automatically publish new images

LICENSE
=> Fix license issue

cmd/adapter/app/start.go
fix #52
Currently, the adapter use http.DefaultClient to access prometheus
instance and it doesn't support https client to access ssl/tls is
enabled prometheus. It is a gap here if prometheus behind a proxy
or prometheus is enable ssl/tls according to official guideline.
This is a common case that prometheus in production, this patch
will fix the gap described above.
=> Add support for auth when connecting to Prometheus

Makefile
Updated Makefile to include changes to the docker-build step, to add support for s390x.
=> Update Makefile to support s390x

docs/walkthrough.md
=> docs: walkthrough, make consistent the volume name

docs/walkthrough.md
=> Fix creating the resource-lister clusterrole

README.md
I'm not sure we need to explain all use cases for both APIs in this README.
What do you think @brancz @s-urbaniak?
=> Update README to container resource metrics API

cmd/adapter/adapter.go
Often prometheus is gated by some proxy requiring an auth bearer
token. Currently there is no possibility to configure one except for
providing a full-fledged kubeconfig.
This fixes it by adding a new flag pointing to an optional file
containing the auth bearer for prometheus communication.
=> cmd/adapter: add prometheus bearer token configuration

README.md
ref: #74 
Signed-off-by: YaoZengzeng <yaozengzeng@zju.edu.cn>
=> faq for namespace prefixed metrics access

README.md
=> Fixed config generation command in README

deploy/manifests/custom-metrics-resource-reader-cluster-role.yaml
link to the issue: 
https://github.com/DirectXMan12/k8s-prometheus-adapter/issues/274#issuecomment-602282471
=> fix forbidden issue #274 by adding appropriate verbs in cluster role

CONTRIBUTING.md, OWNERS.txt, OWNERS_ALIASES.txt, README.md, RELEASE.md, SECURITY.md, SECURITY_CONTACTS.txt, code-of-conduct.md
/cc @lilic @paulfantom @simonpasquier @nikhita
I am not sure if I forgot something, please help me here :-)
@brancz @DirectXMan12 question: would you like to be added to the OWNERS/SECURITY_OWNERS files?
=> *: add Kubernetes templates

README.md
Helm stable repository will be archived on November 13th, so update the helm chars repository in README.
=> Update helm charts repository in README

.travis.yml, Makefile, cmd/adapter/adapter.go, cmd/config-gen/main.go, cmd/config-gen/utils/default.go, go.mod, pkg/client/fake/client.go, pkg/client/metrics/metrics.go, pkg/custom-provider/provider.go, pkg/custom-provider/provider_test.go, pkg/custom-provider/series_registry.go, pkg/custom-provider/series_registry_test.go, pkg/external-provider/basic_metric_lister.go, pkg/external-provider/external_series_registry.go, pkg/external-provider/metric_converter.go, pkg/external-provider/periodic_metric_lister_test.go, pkg/external-provider/provider.go, pkg/naming/metric_namer.go, pkg/naming/metrics_query.go, pkg/naming/metrics_query_test.go, pkg/naming/regex_matcher_test.go, pkg/naming/resource_converter.go, pkg/resourceprovider/provider.go, pkg/resourceprovider/provider_test.go
Fixes a requirement mentioned in #371
/cc @dgrisonnet
=> *: move all imports to github.com/kubernetes-sigs/prometheus-adapter

cmd/adapter/adapter.go
Add a signal handler stopping the adapter if it receives a SIGINT or
SIGTERM signal. This prevent the prometheus-adapter pod from being stuck
in "Terminating" state.
=> Add signal handler

pkg/resourceprovider/provider.go
The code that we are reusing from metrics-server to call
GetContainerMetrics and GetNodeMetrics requires that both functions
return arrays of lengths of the number of pods/nodes given as
arguments. In some cases, prometheus-adapter was returning nil which
caused panics in metrics-server code.
```
I0503 13:58:46.056646       1 adapter.go:98] successfully using in-cluster auth
I0503 13:58:47.390698       1 secure_serving.go:197] Serving securely on [::]:6443
I0503 13:58:47.390944       1 dynamic_cafile_content.go:167] Starting request-header::/etc/tls/private/requestheader-client-ca-file
I0503 13:58:47.390970       1 dynamic_serving_content.go:130] Starting serving-cert::/etc/tls/private/tls.crt::/etc/tls/private/tls.key
I0503 13:58:47.390990       1 tlsconfig.go:240] Starting …
```
=> Prevent metrics-server panics on GetContainerMetrics and GetNodeMetrics

cmd/adapter/adapter.go
Create the pod lister based on a filtered informer factory that will
filter non-running pods so that prometheus-adapter don't expect metrics
from them.
Fixes #402
=> Filter non-running pods

cloudbuild.yaml
Add cloudbuild.yaml file required by the image pushing job according to this [document](https://github.com/kubernetes/test-infra/blob/master/config/jobs/image-pushing/README.md).
Ref: #414
=> Add cloudbuild.yaml

RELEASE.md
Ref: https://github.com/kubernetes-sigs/prometheus-adapter/issues/414
=> RELEASE.md: update with gcr promotion guidelines

docs/externalmetrics.md, docs/sample-config.yaml
Replaced external: by externalRules: in documentation for external rules
=> Fix external rule tag in documentation

README.md
Fixes https://github.com/kubernetes-sigs/prometheus-adapter/issues/429
Signed-off-by: fpetkovski <filip.petkovsky@gmail.com>
=> Document image registries

cmd/adapter/adapter.go
Signed-off-by: Arunprasad Rajkumar <arajkuma@redhat.com>
=> fix: add openapi spec for custom and external metrics types

.travis-deploy.sh
=> Remove unused travis deploy file

RELEASE.md
Related:
- Part of: https://github.com/kubernetes/k8s.io/issues/1597
=> docs: follow kubernetes/k8s.io branch rename:

README.md
Updated for Helm3 command removed "--name"
=> Update README.md with Helm-3 Command

docs/config.md, docs/sample-config.yaml
new here. so this may be wrong. but as far as I can tell, those commas make the yaml invalid....
at least this is what I saw when I ran Prometheus Adapter with that config.
=> Fix yaml in sample config & docs

Dockerfile
=> Fix multiarch image build
